
spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/inventory-service
    password: 123456123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka